# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jodys/c_src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jodys/c_src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jodys/c_src/CMakeFiles /Users/jodys/c_src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jodys/c_src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_alignment

# Build rule for target.
test_alignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_alignment
.PHONY : test_alignment

# fast build rule for target.
test_alignment/fast:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/build
.PHONY : test_alignment/fast

#=============================================================================
# Target rules for targets named test_sw

# Build rule for target.
test_sw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sw
.PHONY : test_sw

# fast build rule for target.
test_sw/fast:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/build
.PHONY : test_sw/fast

src/alignment.o: src/alignment.c.o

.PHONY : src/alignment.o

# target to build an object file
src/alignment.c.o:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/alignment.c.o
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/alignment.c.o
.PHONY : src/alignment.c.o

src/alignment.i: src/alignment.c.i

.PHONY : src/alignment.i

# target to preprocess a source file
src/alignment.c.i:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/alignment.c.i
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/alignment.c.i
.PHONY : src/alignment.c.i

src/alignment.s: src/alignment.c.s

.PHONY : src/alignment.s

# target to generate assembly for a file
src/alignment.c.s:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/alignment.c.s
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/alignment.c.s
.PHONY : src/alignment.c.s

src/score_matrix.o: src/score_matrix.c.o

.PHONY : src/score_matrix.o

# target to build an object file
src/score_matrix.c.o:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/score_matrix.c.o
.PHONY : src/score_matrix.c.o

src/score_matrix.i: src/score_matrix.c.i

.PHONY : src/score_matrix.i

# target to preprocess a source file
src/score_matrix.c.i:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/score_matrix.c.i
.PHONY : src/score_matrix.c.i

src/score_matrix.s: src/score_matrix.c.s

.PHONY : src/score_matrix.s

# target to generate assembly for a file
src/score_matrix.c.s:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/score_matrix.c.s
.PHONY : src/score_matrix.c.s

src/sds/sds.o: src/sds/sds.c.o

.PHONY : src/sds/sds.o

# target to build an object file
src/sds/sds.c.o:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/sds/sds.c.o
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/sds/sds.c.o
.PHONY : src/sds/sds.c.o

src/sds/sds.i: src/sds/sds.c.i

.PHONY : src/sds/sds.i

# target to preprocess a source file
src/sds/sds.c.i:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/sds/sds.c.i
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/sds/sds.c.i
.PHONY : src/sds/sds.c.i

src/sds/sds.s: src/sds/sds.c.s

.PHONY : src/sds/sds.s

# target to generate assembly for a file
src/sds/sds.c.s:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/sds/sds.c.s
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/sds/sds.c.s
.PHONY : src/sds/sds.c.s

src/sw.o: src/sw.c.o

.PHONY : src/sw.o

# target to build an object file
src/sw.c.o:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/sw.c.o
.PHONY : src/sw.c.o

src/sw.i: src/sw.c.i

.PHONY : src/sw.i

# target to preprocess a source file
src/sw.c.i:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/sw.c.i
.PHONY : src/sw.c.i

src/sw.s: src/sw.c.s

.PHONY : src/sw.s

# target to generate assembly for a file
src/sw.c.s:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/sw.c.s
.PHONY : src/sw.c.s

src/test_alignment.o: src/test_alignment.c.o

.PHONY : src/test_alignment.o

# target to build an object file
src/test_alignment.c.o:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/test_alignment.c.o
.PHONY : src/test_alignment.c.o

src/test_alignment.i: src/test_alignment.c.i

.PHONY : src/test_alignment.i

# target to preprocess a source file
src/test_alignment.c.i:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/test_alignment.c.i
.PHONY : src/test_alignment.c.i

src/test_alignment.s: src/test_alignment.c.s

.PHONY : src/test_alignment.s

# target to generate assembly for a file
src/test_alignment.c.s:
	$(MAKE) -f CMakeFiles/test_alignment.dir/build.make CMakeFiles/test_alignment.dir/src/test_alignment.c.s
.PHONY : src/test_alignment.c.s

src/test_sw.o: src/test_sw.c.o

.PHONY : src/test_sw.o

# target to build an object file
src/test_sw.c.o:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/test_sw.c.o
.PHONY : src/test_sw.c.o

src/test_sw.i: src/test_sw.c.i

.PHONY : src/test_sw.i

# target to preprocess a source file
src/test_sw.c.i:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/test_sw.c.i
.PHONY : src/test_sw.c.i

src/test_sw.s: src/test_sw.c.s

.PHONY : src/test_sw.s

# target to generate assembly for a file
src/test_sw.c.s:
	$(MAKE) -f CMakeFiles/test_sw.dir/build.make CMakeFiles/test_sw.dir/src/test_sw.c.s
.PHONY : src/test_sw.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_alignment"
	@echo "... test_sw"
	@echo "... src/alignment.o"
	@echo "... src/alignment.i"
	@echo "... src/alignment.s"
	@echo "... src/score_matrix.o"
	@echo "... src/score_matrix.i"
	@echo "... src/score_matrix.s"
	@echo "... src/sds/sds.o"
	@echo "... src/sds/sds.i"
	@echo "... src/sds/sds.s"
	@echo "... src/sw.o"
	@echo "... src/sw.i"
	@echo "... src/sw.s"
	@echo "... src/test_alignment.o"
	@echo "... src/test_alignment.i"
	@echo "... src/test_alignment.s"
	@echo "... src/test_sw.o"
	@echo "... src/test_sw.i"
	@echo "... src/test_sw.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

